### ISSUE TITLE
Multiple packages link to native library `openssl`

### ISSUE THREAD

**Issue by wilt00** [hello-rust/hello#5]
I'm trying to compile the package, but compilation fails with this error:
```
$ cargo install
warning: To build the current package use `cargo build`, to install the current package run `cargo install --path .`
  Installing hello v0.1.0 (file:///home/wt/dev/hello)
error: failed to compile `hello v0.1.0 (file:///home/wt/dev/hello)`, intermediate artifacts can be found at `/home/wt/dev/hello/target`

Caused by:
  multiple packages link to native library `openssl`, but a native library can be linked only once

package `openssl-sys v0.7.17`
    ... which is depended on by `openssl-sys-extras v0.7.14`
    ... which is depended on by `openssl v0.7.14`
    ... which is depended on by `hyper v0.9.18`
    ... which is depended on by `rawr v0.1.1`
    ... which is depended on by `hello v0.1.0 (file:///home/wt/dev/hello)`
links to native library `openssl`

package `openssl-sys v0.9.33`
    ... which is depended on by `openssl v0.9.24`
    ... which is depended on by `native-tls v0.1.5`
    ... which is depended on by `egg-mode v0.12.0`
    ... which is depended on by `hello v0.1.0 (file:///home/wt/dev/hello)`
also links to native library `openssl`
```
This error also happens when running `cargo build`. Cargo 1.27.0, rustc 1.27.2, toolchain stable-x86_64-unknown-linux-gnu running on WSL in Windows 10.

**Comment by mre** [comment]
Ouch. Sorry for that. openssl can get ugly. Looks like it's coming from the Reddit support; rawr is the Reddit client I use.
Maybe there's a newer version of rawr or we could pin the openssl version somehow. I'll try to reproduce and find out.
If anybody has an idea, feel free to send a PR. 😊

**Comment by mre** [comment]
Updated the rawr version that I use to one that has newer openssl-bindings. Could you try again with the latest master?

**Comment by wilt00** [comment]
Another git clone, and everything works now! Although I did have to tweak `Cargo.toml` so that the version of `rawr` was `0.2.0`.

**Comment by mre** [comment]
Nice to hear and thanks for the bug report. 🎉
